version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: hotel_enigma
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build:
      context: ../php
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  challenge:
    build:
      context: ./challenges
    ports:
      - "5001:5000"
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

