version: '3'
services:
  php_web:
    build:
      context: .
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: hotel_enigma
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
