version: '3'
services:
  web:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=hotel_enigma
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: hotel_enigma
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql



  # node-app:
  #   build: 
  #     context: ./node
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

