version: '3'
services:
  php_web:
    build:
      context: .
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: hotel_enigma
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    ports:
      - "5432:5432"
